#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["observecontext-client"]
# [tool.uv.sources]
# observecontext-client = { git = "https://github.com/pocketcontext/observecontext.git", rev = "d10e84bb30ce607c03c62c03a4fdfd596d32ab27" }
# ///
from observecontext_client.cli import main

raise SystemExit(main())
