#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["observecontext-client"]
# [tool.uv.sources]
# observecontext-client = { git = "https://github.com/pocketcontext/observecontext.git", rev = "7cd33ed2f75a84a11385f5d0ff52b6be99a7c1a0" }
# ///
from observecontext_client.cli import main

raise SystemExit(main())
